#!/usr/bin/env bash

# compile JOOS programs using the A- compiler.

# assumes JOOSDIR is set properly
# assumes a binary called `joos' is on PATH

$PEEPDIR/JOOSA-src/joos $* $PEEPDIR/JOOSexterns/*.joos
