
compiler:
	cd JOOSA-src && $(MAKE)
bench01:
	cd PeepholeBenchmarks/bench01 && $(MAKE) all >  code.size 
bench02:
	cd PeepholeBenchmarks/bench02 && $(MAKE) all >  code.size 
bench03:
	cd PeepholeBenchmarks/bench03 && $(MAKE) all >  code.size 
bench04:
	cd PeepholeBenchmarks/bench04 && $(MAKE) all >  code.size 
bench05:
	cd PeepholeBenchmarks/bench05 && $(MAKE) all >  code.size 
bench06:
	cd PeepholeBenchmarks/bench06 && $(MAKE) all >  code.size 
bench07:
	cd PeepholeBenchmarks/bench07 && $(MAKE) all >  code.size 
