#!/bin/bash
for validinvalid in ./TEST_PROGRAMS/*; do
	for subfolder in $validinvalid/*; do
        for filename in $subfolder/*; do 
        echo "$filename" 
        ./src/goLite.native $filename 
        done
	done
done
        
# done
