#!/bin/bash
for validinvalid in ./TEST_PROGRAMS/VALID_TYPECHECK/*; do
	# for subfolder in $validinvalid/*; do
        # for filename in $validinvalid/*; do 
        echo "$validinvalid" 
        ./src/goLite.native $validinvalid
        # done
	# done
done
        
# done
