package loltypes

type WGQ int32
type lol []struct {A48D, iv84, X2RE [][]WGQ;
            b9H7, ikJe, Vds8 [324]struct {};
            G4y7, d310, bV7K struct {s692 [432]struct {};};}


type w4Z int32
type Esg int32
type zSW int32
type d07 int32
type lol2 [11]struct {MJ01,
                               eP58,
                               Tf3J,
                               Ikuy,
                               L4jD,
                               z640,
                               p7Q5,
                               G808,
                               v1_4,
                               w9_5,
                               U4P1,
                               yuD6,
                               t8l7,
                               Lw74,
                               YGK2,
                               jQ2K []struct {};
                               d0G7,
                               B725,
                               Vb55,
                               q59E,
                               jhjr,
                               j908,
                               Zf9E,
                               AHgR,
                               C01T,
                               u347,
                               wWS5,
                               AkEK,
                               O3N5,
                               qoN5,
                               YkOl,
                               P03H [][]struct {};
                               rDyD,
                               UBZ3,
                               xXr2,
                               a01P,
                               D9h4,
                               U882,
                               R6Yr,
                               TYv8,
                               a5uv,
                               k434,
                               u31a,
                               ao35,
                               dya3,
                               UY8A,
                               su3N,
                               O6V3 [][324]w4Z;
                               g2WB,
                               vYOq,
                               M3_U,
                               h9O2,
                               Q08t,
                               IMB6,
                               Zs26,
                               T7c9,
                               v62g,
                               x8l6,
                               c897,
                               BN81,
                               Clx4,
                               U360,
                               g80a,
                               d74v [55]struct {};
                               K7_9,
                               HfkK,
                               Wv23,
                               n580,
                               SF17,
                               FYCW,
                               oN70,
                               t480,
                               Vzgg,
                               Aer1,
                               iBj5,
                               Dd52,
                               F1r3,
                               kT6u,
                               h24Q,
                               MUkp [44][]struct {};
                               w847,
                               p8Fh,
                               i4z8,
                               Nvzk,
                               H25V,
                               KYZ8,
                               _1zg,
                               zRG7,
                               CXBO,
                               D0n0,
                               k4l2,
                               QpZH,
                               Y139,
                               KA12,
                               L398,
                               f796 [435]struct {};
                               Hk38,
                               Yy5h,
                               qto1,
                               i404,
                               y5wc,
                               j2t2,
                               dEp2,
                               vOB6,
                               h093,
                               A920,
                               Yo6r,
                               W95W,
                               W381,
                               oAHj,
                               Jox_,
                               ZpzY [523]struct {};
                               vRdL,
                               q77W,
                               p7Uy,
                               C55O,
                               R246,
                               TC_H,
                               S3w5,
                               P5E2,
                               rr4u,
                               x3l1,
                               eUnq,
                               M9i0,
                               kA63,
                               hEaV,
                               Pg10,
                               N55M [][35]struct {};
                               e7RO,
                               RL25,
                               eY4Q,
                               XUG1,
                               M3RA,
                               cyZ1,
                               Y8P0,
                               Fmc2,
                               h4J2,
                               bzdB,
                               h4V6,
                               RtT0,
                               u7Ho,
                               jLbY,
                               k3a3,
                               Y3KW [123][432]struct {};
                               OIK1,
                               s747,
                               a90W,
                               mZH2,
                               MqoH,
                               PHw3,
                               dC36,
                               u6w2,
                               TL9K,
                               Ll9t,
                               T31B,
                               x827,
                               zF61,
                               h5QU,
                               We8X,
                               FwC_ struct {Wu63 [345][]Esg;};
                               GyR3,
                               o7H9,
                               cB85,
                               ePas,
                               QC89,
                               HKGR,
                               E3J3,
                               jK61,
                               O36x,
                               s4tz,
                               t657,
                               p3cN,
                               y239,
                               ZBA7,
                               ApE8,
                               MO74 [][124]struct {};
                               z78E,
                               nG7z,
                               Pf47,
                               rJ3S,
                               jdp7,
                               T297,
                               l5vm,
                               x8kH,
                               Xl80,
                               C45d,
                               qVKq,
                               F0N3,
                               SX49,
                               i304,
                               o24H,
                               UZ7U [12][]zSW;
                               Shvp,
                               F1XO,
                               HxE0,
                               f_5C,
                               pgNv,
                               skCI,
                               R28c,
                               rCB9,
                               KwB1,
                               K7u4,
                               owV9,
                               JjK7,
                               TOTD,
                               ZLLv,
                               H73p,
                               t719 struct {vk6p [2]struct {};};
                               B3bK,
                               UDto,
                               eY6x,
                               F8WE,
                               n9z1,
                               vl05,
                               e498,
                               CK88,
                               K971,
                               qj43,
                               e551,
                               s069,
                               B089,
                               r40n,
                               nOP3,
                               L7wq [234]struct {};
                               SbX6,
                               s8I5,
                               _9K5,
                               HwQa,
                               LLir,
                               I242,
                               t572,
                               M0t0,
                               j194,
                               Q04J,
                               C15T,
                               G1XQ,
                               q6H8,
                               Bivk,
                               lU86,
                               W7WV struct {E583 [654][67]d07;};
                               B1t2,
                               WV03,
                               ooQv,
                               F16v,
                               x2Am,
                               Mar5,
                               q0Y1,
                               N948,
                               Mpju,
                               Zj39,
                               iSh5,
                               v3sX,
                               J235,
                               pL70,
                               x930,
                               mPFf [321]struct {};}

func main() {
    print(":)")
}
